In [1]:
import numpy as np
import time
import os
import faiss


In [2]:
data_features=np.load("final_embeddings_top.npy")


In [3]:
pwd

'/recsys-data/Modelling/ashutosh'

In [4]:
em500 =data_features[0:500]
em1k =  data_features[0:1000]
em2k = data_features[0:2000] 
em5k = data_features[0:5000] 
em10k =  data_features[0:1000]

In [5]:
em_dict = {'em500':em500,
           'em1k':em1k,
           'em2k':em2k,
           'em5k':em5k,
           'em10k':em10k}

In [6]:
 
os.chdir('/recsys-data/Modelling/ashutosh/fiass_files')
nlist =100

k =100
d=2048 
for results in em_dict.keys():
    print("Building search index and adding vectors to index")
    start = time.time()
    quantizer = faiss.IndexFlatL2(d)
    print("a")
    index = faiss.IndexIVFFlat(quantizer, d, nlist,faiss.METRIC_L2)
    print("b")
    assert not index.is_trained
    index.train(em_dict[results])
    assert index.is_trained
   
    index.add(em_dict[results]) 
   
    file_name = 'model2_'+results+'_'+'.index'
    print("[!] Saving the index to",file_name)
    faiss.write_index(index,file_name)
    print('[!] Faiss building time = %.3f\n\n\n'%(time.time()-start))

Building search index and adding vectors to index
a
b
[!] Saving the index to model2_em500_.index
[!] Faiss building time = 0.265



Building search index and adding vectors to index
a
b
[!] Saving the index to model2_em1k_.index
[!] Faiss building time = 0.059



Building search index and adding vectors to index
a
b
[!] Saving the index to model2_em2k_.index
[!] Faiss building time = 0.094



Building search index and adding vectors to index
a
b
[!] Saving the index to model2_em5k_.index
[!] Faiss building time = 0.243



Building search index and adding vectors to index
a
b
[!] Saving the index to model2_em10k_.index
[!] Faiss building time = 0.209





In [7]:
nProbe=1
k=4
xq=em500[2:3]
for file in em_dict.keys():
    print('model2_'+file+"_"+".index")
    index=faiss.read_index('model2_'+file+"_"+".index")
    start = time.time()
    D,I =index.search(xq, k)
    print (I)
    print (D)
    print('Execution time for = %.5f\n\n'%(time.time()-start))

model2_em500_.index
[[  2   8 464   4]]
[[  0.      133.64337 216.89291 229.85953]]
Execution time for = 0.07663


model2_em1k_.index
[[  2   8 914 517]]
[[  0.      133.64337 202.28752 208.40193]]
Execution time for = 0.00136


model2_em2k_.index
[[   2    8 1363  966]]
[[  0.      133.64337 190.48993 213.63504]]
Execution time for = 0.00102


model2_em5k_.index
[[   2 4254 3648 3185]]
[[  0.      192.18214 196.00598 203.44588]]
Execution time for = 0.00109


model2_em10k_.index
[[  2   8 914 517]]
[[  0.      133.64337 202.28752 208.40193]]
Execution time for = 0.00106


